"use client"
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/layout/Navbar";
import Footer from "../components/layout/Footer";
import Alert from "../components/layout/Alert";
import { GitHubProvider } from "../context/github/GithubContext";
import { AlertProvider } from "@/context/alert/AlertContex.js";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Github Finder",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GitHubProvider>
          <AlertProvider>
            <div className="flex bg-gray-600 text-gray-100 flex-col justify-between min-h-screen">
        <Navbar />
              <Alert />
        <main className='container mx-auto px-3 pb-12'>
        {children}
        </main>
        <Footer/>
     </div>
      </AlertProvider>
        </GitHubProvider>
        </body>
    </html>
  );
}
